name: Continuous Integration

on:
  pull_request:
    branches: [develop, staging, master]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run built
